### ISSUE TITLE
Consecutive transfers

### ISSUE THREAD

**Issue by Gigi3d** [bitmask-stack/bitmask-core#140]
ACs:

- [ ] Can transfer a token multiple times, one after another (consecutively)
- [ ] Can create a new receive outpoint after the spend outpoint is spent
- [ ] Can track multiple asset outputs in the wallet so it can be recovered from a mnemonic

**Comment by cryptoquick** [comment]
I'm not sure we have well-defined behavior around this problem. Conceptually, the vault is just a set of UTXOs we can mint and receive assets on, and so funding the vault might not be the right name for this; instead, maybe "create vault" or "start vault" ?

It's not really an account per se, the vault is not an address; it's a UTXO that can, for a time, receive assets, unless it's spent, then it can no longer receive assets, and all assets are transferred to a new one. Assets shouldn't be lost if sent to a spent tx output, since transfer is an atomic operation.

Presently, we don't handle making new change UTXOs well after a transfer (multiple transfers of a token, one after the other), but I think it's kind of assumed that the wallet will use any sats in the main bitcoin on-chain wallet as-needed. There is also a related question of how we order and persist outputs for a new change UTXO.

**Comment by josediegorobles** [comment]
I think Create vault is a better description and yeah I don't see necessary notifications of it running low. The sats necessaries for change must be take from the main wallet.
The point made by @cryptoquick are correct and necessary to have a good management of the vault

**Comment by Gigi3d** [comment]
This is way  better and less complicated than I thought. We can close this issue i presume?

**Comment by cryptoquick** [comment]
I'd prefer to repurpose this issue, since it effectively encapsulates some thinking we still need to do in order to support multiple transfers.

**Comment by cryptoquick** [comment]
I'll be renaming the vault details so that the receive outpoints have been renamed spend, and change outpoints renamed to receive. Then, I think there might be a way to determine which outpoint is which just by looking at past transactions for each asset vault wallet, we'd just need to do the funding transactions in a different way. If we do them with the old output, plus using an output from the bitcoin wallet for fees, then we can create a new receive output, and then an output sending the remainder back as change to the latest bitcoin wallet change address. This might work... I won't know unless I try, though.

We will know which outpoint is which through the convention that the transaction prior's receive outpoint is now the new spend outpoint, and the new receive outpoint is the outpoint that does not belong to the bitcoin wallet, according to this: https://docs.rs/bdk/latest/bdk/wallet/struct.Wallet.html#method.get_tx

Also, we should use separate methods for the assets vault and UDAs vault, so that it's not checking two wallets at once, which should make it faster.

**Comment by oacdutra** [comment]
Bugs related:

 * https://github.com/BP-WG/t/issues/1
 * https://github.com/RGB-WG/rgb-wallet/issues/47
