### ISSUE TITLE
replace Esplora::broadcast with direct request

### ISSUE THREAD

**Issue by josediegorobles** [bitmask-stack/bitmask-core#365]
When the error reported here: https://github.com/diba-io/bitmask-core/issues/364 and maybe in other occasions, all process are done but the transaction is not sent to the blockchain.

So, we need:

- [ ] verify_transfers if after some minutes the transactions is not in the mempool nor confirmed, we have to delete the transfer from the list
- [ ] list_contracts in AllocationDetail we need another property, onChain or inMempool, or something like that so if there are a transactions that we can't see yet, we don't take account this transaction

**Comment by cryptoquick** [comment]
Thank you for filing this, I've been experiencing the same issues.

**Comment by oacdutra** [comment]
The problem occurs because the PSBT was created with wrong way (Please, see PR bitcoindevkit/bdk#366 ). 

Also, `ExploraBlockchain::broadcast` method is badly to troubleshooting transaction error, because the method does not display the problem that caused the `badrequest`:.

```rust
/// Broadcast a [`Transaction`] to Esplora
pub async fn broadcast(&self, transaction: &Transaction) -> Result<(), Error> {
    self.client
        .post(&format!("{}/tx", self.url))
        .body(serialize(transaction).to_hex())
        .send()
        .await?
        .error_for_status()?;

    Ok(())
}
```

I suggest changing this issue to "replace Esplora::broadcast with direct request"
