### ISSUE TITLE
Testnet Lightning Support

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#8]
Tracking issue for Lightning support

- [x] #89
- [x] #90
- [x] #91

Mainnet Lightning support to come later.

**Comment by grunch** [comment]
Bitmask wallet should be able to send and receive lightning network payments, there are several ways to accomplish that, the ideal solution is to build a self-custodial wallet, but this requires to solve a lot of important issues that the users will have like maintaining users liquidity, allowing users to send and receive sats at any time, no matter which side of the channel have the funds, these are some of the issues to solve, creating a self-custodial wallet is a long way to go, this is why we think we can start working on a custodial solution where we can bring a good user experience, we can re-evaluate in the future if we are ready to jump to a self-custodial wallet.

Instead of creating by ourselves a new system of LN custodial wallets for each user we can use a great project which is being tested for years called [lndHub](https://github.com/BlueWallet/LndHub), developed by Bluewallet team, I have couple of days testing it and I like it.

This methods will allow bitmask to connect with lndHub
https://github.com/diba-io/bitmask-core/blob/7e7a455b33a9eb2c9ef7f3f236c6e3e1ca3d8666/src/util.rs#L63-L98


List of issues to do
- [ ] Add new env var to store the lndHub URL
- [ ] Add new functions and tests to create new wallets 
- [ ] Add new functions and tests to ask for a new access_token
- [ ] Add new functions and tests to decode an invoice
- [ ] Add new functions and tests to check invoice route (Check if payment destination is available and invoice could be paid)
- [ ] Add new functions and tests to pay an invoice
- [ ] Add new functions and tests to get wallet balance


I have doubts on how bitmask works, if I write a function to create a wallet on lndHub with a POST to http://127.0.0.1/create how I handle the target_arch = "wasm32" ? I mean, this condition is for only compile when we generate wasm, how we specify the arch? do you have some links where I can understand how wasm works on bitmask?

**Comment by cryptoquick** [comment]
Fantastic work summarizing our discussion, @grunch. The `get` and `post_json` methods have versions that work in both wasm and desktop. I recommend starting with an ordinary desktop test, kind of like how I test in `tests/asset.rs`, and then we can focus on exposing those methods to wasm later. Does that makes sense?

**Comment by grunch** [comment]
makes a lot of sense, I will be asking more questions... later 😄
